### PR TITLE
Removed depends on imx4-demos and compile/install imx4-image as not provided

### PR DESCRIPTION
**Pull request by ghost**
Removed deploy IMX_M4_demos as not provided
Removed compile and install m4_image.bin

### CODE REVIEW

**Comment by abelal** [comment]
@muhamzai please update the commit message, this does not follow the guidelines which is generally > https://confluence.alm.mentorg.com/display/MEL/MEL+commit+message+policy

**Comment by ghost** [comment]
on it

**Comment by ghost** [comment]
Updated commit message

**Comment by abelal** [comment]
It still isn't following the guidelines :slightly_smiling_face:

> First line should be summary of the change and it should start with the file name or component that has changes. It should not be more than 60 characters long including the component.

`imx-boot_0.2.bb: removed depends on imx4-demos and compile/install imx4-image`

is 78 chars

`imx-boot: remove dependency on imx4-demos`

might be good enough.

> Then comes the detailed message of the change. Each line should not be greater than 72 characters. describe each change from new line.

and there's no detail provided to satisfy this. Something like

```
We do not need the imx m4 demos on target as we do not demo
that functionality and this also pulls in extra stuff into the target image
so we simply drop these.
```

would be sufficient and there's also a typo in "Signed-of-by". So overall the commit would look like

```
imx-boot: remove dependency on imx4-demos

We do not need the imx m4 demos on target as we do not demo
that functionality and this also pulls in extra stuff into the target image
so we simply drop these.

Signed-off-by: Muhammad Hamza <muhammad_hamza@mentor.com>
```

**Comment by ghost** [comment]
right, updated

**Review by abelal — APPROVED** [review]

**Pull request closed without merging**
